### ISSUE TITLE
FeatueTable only reading?

### ISSUE THREAD

**Issue by krank42** [Esri/feature-service-editor-js#17]
I read that the FeatureTable | API Reference | ArcGIS API for JavaScript is not editable - read only? Is this true?

**Comment by andygup** [comment]
Yes, that's true in v3.13. I'm checking into when that functionality will be made available. Sounds like you need table editing capabilities? 

You are welcome to fork/use/modify this code to make it work with your requirements. I'm not planning on updating it, however. But I can try to answer questions.

**Comment by krank42** [comment]
Yes, I need these editing capabilities. In ArcGis for Portal it is sometimes not so comfortable!

**Comment by andygup** [comment]
Your best bet is going to be building a custom app/widget, if you need something immediately. 

There are coding patterns in this repo that could save you a lot of time.
